apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
  - ../../base
  - resources/ingress.yaml
  - resources/certificate.yaml
  - ../../../payment-integration/overlays/hackathon

patchesStrategicMerge:
  - patches/frontend-service-patch.yaml

patches:
  - path: patches/remove-payment.yaml