apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bank-of-anthos

resources:
  - ../../base
  - resources/ingress.yaml
  - resources/certificate.yaml

patches:
  - path: patches/frontend-service-patch.yaml
    target:
      kind: Service
      name: frontend
  - path: patches/statefulset-sa-fix.yaml
    target:
      kind: StatefulSet
      name: accounts-db
  - path: patches/statefulset-sa-fix.yaml
    target:
      kind: StatefulSet
      name: ledger-db
  - path: patches/disable-tracing.yaml
    target:
      kind: ConfigMap
      name: environment-config