apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: bank-of-anthos
data:
  ENABLE_TRACING: "false"
  ENABLE_METRICS: "false"
  LOCAL_ROUTING_NUM: "123456789"
  PUB_KEY_PATH: "/tmp/.ssh/publickey"