apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bank-of-anthos

resources:
  - ../../base
  - resources/ingress.yaml

patches:
  - path: patches/frontend-service-patch.yaml
    target:
      kind: Service
      name: frontend