apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bank-gke10-candaele-dev-tls
  namespace: bank-of-anthos
spec:
  secretName: bank-gke10-candaele-dev-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
  - bank.gke10.candaele.dev