apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boutique-gke10-candaele-dev-tls
  namespace: online-boutique
spec:
  secretName: boutique-gke10-candaele-dev-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
  - boutique.gke10.candaele.dev