apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: domains@candaele.dev
    privateKeySecretRef:
      name: letsencrypt-http01-key
    solvers:
    - http01:
        ingress:
          class: nginx