apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - jwt-secret.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: payment-integration
    newName: payment-integration
    newTag: latest