apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP
  selector:
    app: payment-integration
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc